accounts/urls.py
from django.urls import path, include
from django.contrib.auth import views as auth_views
from .views import LoginView, RegisterView


app_name = 'accounts'
urlpatterns = [
    path('login/', LoginView.as_view(), name = 'login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('register/', RegisterView.as_view(), name = 'register'),
]

carts/urls.py
from django.urls import path, include

from .views import cart_home, cart_update, checkout_home, CartSuccess, AddressUpdate
app_name = 'carts'
urlpatterns = [
    path('', cart_home, name='home'),
    path('update/', cart_update, name='update'),
    path('checkout/', checkout_home, name='checkout'),
    path('success/', CartSuccess.as_view(), name = 'success'),
    path('address-update/<int:pk>/',  AddressUpdate.as_view(), name = 'address_update')
]

ecommerce/urls.py
from django.conf.urls.static import static
from django.conf import settings
from django.contrib import admin
from django.urls import path, include
from .views import HomePage

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', HomePage.as_view(), name = 'index'),
    path('accounts/', include('accounts.urls')),
    path('products/', include('products.urls')),
    path('search/', include('search.urls')),
    path('carts/', include('carts.urls')),
    path('billing/', include('billing.urls')),
    path('analytics', include('analytics.urls'))
]


if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

products/urls.py
from django.urls import path, include

from .views import ProductListView, ProductDetailView, GroupListView

app_name = 'product'
urlpatterns = [
    path('', ProductListView.as_view(), name = 'list'),
    path('group/<int:pk>', GroupListView.as_view(), name = 'group_list' ),
    path('<str:slug>', ProductDetailView.as_view(), name = 'details'),
]

carts/models.py
from django.db import models
from django.conf import settings
from products.models import Product
from django.db.models.signals import pre_save, post_save, m2m_changed

User = settings.AUTH_USER_MODEL

class CartManager(models.Manager):

    def get_or_create():
        return obj, True

    def new_or_get(self,request):
        cart_id = request.session.get('cart_id',None)
        qs = self.get_queryset().filter(id=cart_id)
        if qs.count() == 1:
            new_obj = False
            cart_obj = qs.first()
            if request.user.is_authenticated and cart_obj.user is None:
                cart_obj.user = request.user
                cart_obj.save()
        else:
            cart_obj = Cart.objects.new(user=request.user)
            new_obj = True
            request.session['cart_id']= cart_obj.id
        return cart_obj, new_obj

    def new(self, user = None):
        user_obj = None
        if user is not None:
            if user.is_authenticated:
                user_obj = user
        return self.model.objects.create(user=user_obj)


class Cart(models.Model):
    user        = models.ForeignKey(User, null=True,blank=True, on_delete=models.CASCADE)
    products    =  models.ManyToManyField(Product, blank=True)
    subtotal    = models.DecimalField(default=0.00, max_digits = 100, decimal_places = 2)
    total       = models.DecimalField(default=0.00, max_digits = 100, decimal_places = 2)
    updated     = models.DateTimeField(auto_now=True)
    timtestamp  = models.DateTimeField(auto_now_add = True)

    objects = CartManager()

    def __str__(self):
        return str(self.id)


def m2m_cart_receiver(sender, instance, action, *args, **kwargs):
    if action[:4] =='post':
        products = instance.products.all()
        total = 0
        for item in products:
            total += item.price
        if instance.subtotal != total:
            instance.subtotal = total
            instance.save()

m2m_changed.connect(m2m_cart_receiver, sender=Cart.products.through)

def pre_save_cart_receiver(sender, instance, *args, **kwargs):
    if instance.subtotal > 0:
        instance.total = instance.subtotal + 10
    else:
        instance.total = 0.00

pre_save.connect(pre_save_cart_receiver, sender=Cart)

carts/views.py
from django.shortcuts import render, redirect
from django.urls import reverse_lazy
from django.forms.models import model_to_dict
from django.views.generic import TemplateView
from django.views.generic.edit import UpdateView
from django.http import JsonResponse



from .models import Cart
from products.models import Product
from orders.models import Order
from billing.models import BillingProfile, Address
from billing.forms import AddressForm
from accounts.forms import LoginForm, GuestForm


# Create your views here.

def cart_home(request):
    cart_obj, new_obj = Cart.objects.new_or_get(request)

    return render(request, 'carts/carts_home.html', {"cart": cart_obj})

def cart_update(request):
    if request.is_ajax():
        print(request.POST)
        product_id = request.POST.get('product')
        if product_id is not None:
            try:
                object = Product.objects.get(id=product_id)
            except Product.DoesNotExist:
                return redirect('cart:home')
            cart_obj, new_obj = Cart.objects.new_or_get(request)
            if object in cart_obj.products.all():
                cart_obj.products.remove(object)
                added = False
            else:
                cart_obj.products.add(object)
                added = True
        request.session['cart_item']= cart_obj.products.count()
        amount_in_cart = cart_obj.products.count()
        data = {'added': added,
                'counter': amount_in_cart}
        return JsonResponse(data)

    product_id = request.POST.get('product')
    if product_id is not None:
        try:
            object = Product.objects.get(id=product_id)
        except Product.DoesNotExist:
            return redirect('cart:home')
        cart_obj, new_obj = Cart.objects.new_or_get(request)
        if object in cart_obj.products.all():
            cart_obj.products.remove(object)
            added = False
        else:
            cart_obj.products.add(object)
            added = True
    request.session['cart_item']= cart_obj.products.count()
    amount_in_cart = cart_obj.products.count()

    return redirect("carts:home")


def checkout_home(request):
    cart_obj, cart_created = Cart.objects.new_or_get(request)
    if cart_created or cart_obj.products.count()==0:
        return redirect('carts:home')
    else:
        order_obj = Order.objects.filter(cart=cart_obj)
        if order_obj.count()==0:
            order_obj =Order(cart=cart_obj)
            order_obj.save()
        else:
            order_obj = order_obj.first()
    user = request.user

    if user.is_authenticated:
        billing_profile = user.billing_profile
        order_obj.billing = billing_profile
        order_obj.save()
    elif 'billing_profile' in request.session.keys():
        if list(request.session.values()):
            billing_profile = BillingProfile.objects.get(pk=list(request.session.values())[2])
            order_obj.billing = billing_profile
            order_obj.save()
        else:
            billing_profile = None
    else:
        guest_form = GuestForm(request.POST)
        billing_profile = None
        if guest_form.is_valid():
            email = guest_form.cleaned_data['email']
            billing_profile = BillingProfile(email=email)
            billing_profile.save()

            request.session['billing_profile'] = billing_profile.id
            order_obj.billing = billing_profile
            order_obj.save()

    if billing_profile:
        if billing_profile.address:
            address = billing_profile.address
        else:
            address_form = AddressForm(request.POST)
            if address_form.is_valid():
                address = address_form.save()
                billing_profile.address = address
                billing_profile.save()
            else:
                address = None
    else:
        address = None

    if request.method == 'POST':
        if 'success' in request.POST:
            order_obj.status = 'paid'
            order_obj.save()
            return redirect('carts:success')

    form = LoginForm()
    guest_form = GuestForm()
    address_form = AddressForm()

    context = {
        "order": order_obj,
        "billing_profile": billing_profile,
        'form': form,
        'guest_form': guest_form,
        'address_form': address_form,
        'address': address
    }
    return render(request, 'carts/checkout.html', context)


class CartSuccess(TemplateView):
    template_name = 'carts/success.html'


class AddressUpdate(UpdateView):
    model = Address
    fields = ['street','city', 'phone']
    template_name = 'carts/address_update.html'
    success_url = reverse_lazy('carts:checkout')

carts/templates/carts/address_update.html
{% extends "base.html" %}
{% block content %}
{% load bootstrap4 %}
<form method="post" >
  {% csrf_token %}
  {% bootstrap_form form  %}
  <input type="submit" class = 'btn btn-default' value="Change address">
</form>


{% endblock %}

carts/templates/carts/carts_home.html
{% extends "base.html" %}
{% block content %}
{% load bootstrap4 %}
{% if cart.products.exists %}
<table class="table">
  <thead>
    <tr>
      <th scope="col">#</th>
      <th scope="col">Product photo</th>
      <th scope="col">Product Name</th>
      <th scope="col">Product Price</th>
    </tr>
  </thead>
  <tbody>
    {% for product in cart.products.all %}

    <tr>

      <th scope="row">{{forloop.counter}}</th>

      {% if product.image %}

        <td><a href='{% url "product:details" slug=product.slug %}'><img src="{{product.image.url}}" alt='' style='height: 50px; width:50px'></a></td>
      {% else %}
      <td><img src="/media/products/Profile-NotAvailable-300x300.png" alt="" style='height: 50px; width:50px'></td>
      {% endif %}

      <td><a href='{% url "product:details" slug=product.slug %}'>{{product.title}}</a></td>
      <td><a href='{% url "product:details" slug=product.slug %}'>{{product.price}}$</a></td>
      <td>{% include 'carts/snippets/delete.html' %}</td>

    </tr>

    {% endfor %}
    <tr>
      <td colspan='2'> </td>
      <td><b>Subtotal</b></td><td>{{cart.subtotal}}</td>
    </tr>
    <tr>
      <td colspan='2'> </td>
      <td><b>Total</b></td><td>{{cart.total}}</td>
      <td><a class = 'btn btn-primary' href="{% url 'carts:checkout' %}" >Order!</a></td>
    </tr>
  </tbody>
</table>
{% else %}
<p class='lead'> Cart is empty </p>
{% endif %}

{% endblock %}

carts/templates/carts/checkout.html
{% extends "base.html" %}
{% block content %}
{% load bootstrap4 %}

{% if not billing_profile%}
<div class='row text-center'>
<div class='col-12 col-md-6'>
<p class='lead'>Login</p>
 <form method="post" action='{% url "accounts:login" %}'>
   <input type="hidden" name='checkout' value="checkout">
   {% csrf_token %}
   {% bootstrap_form form  %}
   <input type="submit" class = 'btn btn-default' value="Sign up">
 </form>
</div>
<div class='col-12 col-md-6'>
  <p class='lead'>Continue as guest</p>
  <form method="post">
    <input type="hidden" name='guest' value="guest">
    {% csrf_token %}
    {% bootstrap_form guest_form  %}
    <input type="submit" class = 'btn btn-default' value="Sign up">
  </form>
</div></div>
{% elif not address %}
<div class='row text-center'>
<div class='col-12 col-md-6'>
<p class='lead'>Login</p>
 <form method="post" >
   <input type="hidden" name='address' value="address">
   {% csrf_token %}
   {% bootstrap_form address_form  %}
   <input type="submit" class = 'btn btn-default' value="Add address">
 </form>
</div>
</div>

{% else %}
{{address}}
<h1>Checkout </h1>
<div class='row text-center'>
<div class='col-8 col-md-6'>
<table class="table">
  <thead>
    <tr>
      <th scope="col">#</th>
      <th scope="col">Product photo</th>
      <th scope="col">Product Name</th>
      <th scope="col">Product Price</th>
    </tr>
  </thead>
  <tbody>
    {% for product in order.cart.products.all %}

    <tr>

      <th scope="row">{{forloop.counter}}</th>

      {% if product.image %}

        <td><a href='{% url "product:details" slug=product.slug %}'><img src="{{product.image.url}}" alt='' style='height: 50px; width:50px'></a></td>
      {% else %}
      <td><img src="/media/products/Profile-NotAvailable-300x300.png" alt="" style='height: 50px; width:50px'></td>
      {% endif %}

      <td><a href='{% url "product:details" slug=product.slug %}'>{{product.title}}</a></td>
      <td><a href='{% url "product:details" slug=product.slug %}'>{{product.price}}$</a></td>


    </tr>

    {% endfor %}
    <tr>
      <td colspan='2'> </td>
      <td><b>Subtotal</b></td><td>{{order.cart.subtotal}}</td>
    </tr>
    <tr>
      <td colspan='2'> </td>
      <td><b>Total</b></td><td>{{order.cart.total}}</td>

    </tr>
  </tbody>
</table>
</div>
<div class='col-4 col-md-4'>
<table class="table">
  <tbody>
    <tr>
      <td scope="row">Street</td> <td>{{address.street}} </td>
    </tr>
    <tr>
      <td scope="row">City</td> <td>{{address.city}} </td>
    </tr>
    <tr>
      <td scope="row">Phone</td> <td>{{address.phone}} </td>
    </tr>
    <tr>
      <td>
      <form method="post" >
        {% csrf_token%}
        <input type="hidden" name='success' value="success">
        <input type="submit" class = 'btn btn-primary' value="Finalize">
      </form>
      </td>
      <td><a class = 'btn btn-alert' href="{% url 'carts:address_update' pk=order.billing.address.pk %}" >Change address</a></b></td>
    </tr>
  </tbody>
</table>
</div></div></div>
{% endif %}

{% endblock %}

carts/templates/carts/success.html
{% extends "base.html" %}
{% block content %}
{% load bootstrap4 %}
<h1> THANK U</h1>



<script>


setTimeout(function() {
      window.location.href = window.location.origin;
    }, 8000);


</script>
{% endblock %}