carts/urls.py
from django.urls import path, include

from .views import cart_home, cart_update, checkout_home, CartSuccess, AddressUpdate
app_name = 'carts'
urlpatterns = [
    path('', cart_home, name='home'),
    path('update/', cart_update, name='update'),
    path('checkout/', checkout_home, name='checkout'),
    path('success/', CartSuccess.as_view(), name = 'success'),
    path('address-update/<int:pk>/',  AddressUpdate.as_view(), name = 'address_update')
]

ecommerce/urls.py
from django.conf.urls.static import static
from django.conf import settings
from django.contrib import admin
from django.urls import path, include
from .views import HomePage

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', HomePage.as_view(), name = 'index'),
    path('accounts/', include('accounts.urls')),
    path('products/', include('products.urls')),
    path('search/', include('search.urls')),
    path('carts/', include('carts.urls')),
    path('billing/', include('billing.urls')),
    path('analytics', include('analytics.urls'))
]


if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

products/urls.py
from django.urls import path, include

from .views import ProductListView, ProductDetailView, GroupListView

app_name = 'product'
urlpatterns = [
    path('', ProductListView.as_view(), name = 'list'),
    path('group/<int:pk>', GroupListView.as_view(), name = 'group_list' ),
    path('<str:slug>', ProductDetailView.as_view(), name = 'details'),
]

products/models.py
from django.db import models
from django.db.models.signals import pre_save
from django.urls import reverse
# Create your models here.

class ProductQuerySet(models.query.QuerySet):
    def featured(self):
        return self.filter(featured=True)

class ProductManager(models.Manager):
    def get_queryset(self):
        return ProductQuerySet(self.model, using = self.db)
    def features(self):
        return self.get_queryset().filter(featured=True)


GROUPS_CHOICES = (
    ('women', 'Women'), ('men', "Men"), ("kids", "Kids"), ("sport", "Sports")
)

TAGS_CHOICES = (
    ('t-shirt', 'T-Shirt'), ('shirt', "Shirt"), ("jeans", "Jeans"), ("shoes", "Shoes"), ('accessories', "Accessories"),
    ('bike', 'Bike'), ('weights', "Weights")
)


class Tags(models.Model):
    name = models.CharField(max_length = 255, choices=TAGS_CHOICES, unique=True)
    def __str__(self):
        return self.name


class Category(models.Model):
    name = models.CharField(max_length = 255, choices=GROUPS_CHOICES, unique=True)
    tags = models.ManyToManyField(Tags,related_name="tags")
    def __str__(self):
        return self.name


class Product(models.Model):
    title = models.CharField(max_length = 255)
    slug = models.SlugField(unique=True)
    description = models.TextField()
    price = models.DecimalField(decimal_places=2, max_digits=20, default = 0)
    image = models.ImageField(upload_to='products', null=True, blank=True)
    category = models.ManyToManyField(Category, blank=True, null=True)
    tags = models.ForeignKey(Tags, blank=True, null=True,on_delete=models.SET_NULL)
    active = models.BooleanField(default=True)
    timestamp = models.DateTimeField(auto_now_add = True)

    objects = ProductManager()

    def get_absolute_url(self):
        return reverse("product:details", kwargs={'slug':self.slug})

    def __str__(self):
        return self.title




def product_pre_save_receiver(sender, instance, *args, **kwargs):
    i = 1
    while not instance.slug:
        instance.slug = instance.name + '-' + str(i)
        i +=0

#2.12
pre_save.connect(product_pre_save_receiver, sender = Product)

products/views.py
from django.shortcuts import render
from django.views.generic import ListView, DetailView
# Create your views here.
from .models import Product, Category
from carts.models import Cart

class ProductListView(ListView):
    model = Product

class ProductDetailView(DetailView):
    model = Product
    def get_context_data(self,*args,**kwargs):
        context = super(ProductDetailView, self).get_context_data(*args, **kwargs)
        cart_obj, new_obj = Cart.objects.new_or_get(self.request)
        context['cart'] = cart_obj
        return context

class GroupListView(ListView):
    model = Category
    

products/templates/products/snippets/card.html
<div class='col'>

<div class="card" style="width: 18rem;">
{% if product.image %}
  <img class="card-img-top" src="{{product.image.url}}" alt="" style="height: 18rem;">
{% else %}
<img class="card-img-top" src="/media/products/Profile-NotAvailable-300x300.png" alt="" style="height: 18rem;">
{% endif %}
  <div class="card-body">
    <h5 class="card-title">{{product.title}}</h5>
    <p class="card-text">{{product.price}} $</p>
    <p class="card-text">{{product.description | truncatewords:10}}</p>
  
    <a href="{% url 'product:details' slug=product.slug %}" class="btn btn-primary">See</a>

  </div>
</div>
</div>

products/templates/products/snippets/update-cart.html
<form class="form ajax-cart" method="POST" action ='{% url "carts:update" %}' class="search-form">
    {% csrf_token %}
    <input type='hidden' name='product' value='{{product.id}}' />
    <div class='form-changer'>
       {% if object in cart.products.all %}
          <button type="submit" name="button" class='btn btn-danger'>Remove?</button>
       {% else %}
          <button type="submit" name="button" class='btn btn-success'>Add?</button>
       {% endif %}
     </div>
</form>