accounts/urls.py
from django.urls import path, include
from django.contrib.auth import views as auth_views
from .views import LoginView, RegisterView


app_name = 'accounts'
urlpatterns = [
    path('login/', LoginView.as_view(), name = 'login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('register/', RegisterView.as_view(), name = 'register'),
]

carts/urls.py
from django.urls import path, include

from .views import cart_home, cart_update, checkout_home, CartSuccess, AddressUpdate
app_name = 'carts'
urlpatterns = [
    path('', cart_home, name='home'),
    path('update/', cart_update, name='update'),
    path('checkout/', checkout_home, name='checkout'),
    path('success/', CartSuccess.as_view(), name = 'success'),
    path('address-update/<int:pk>/',  AddressUpdate.as_view(), name = 'address_update')
]

ecommerce/urls.py
from django.conf.urls.static import static
from django.conf import settings
from django.contrib import admin
from django.urls import path, include
from .views import HomePage

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', HomePage.as_view(), name = 'index'),
    path('accounts/', include('accounts.urls')),
    path('products/', include('products.urls')),
    path('search/', include('search.urls')),
    path('carts/', include('carts.urls')),
    path('billing/', include('billing.urls')),
    path('analytics', include('analytics.urls'))
]


if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

products/urls.py
from django.urls import path, include

from .views import ProductListView, ProductDetailView, GroupListView

app_name = 'product'
urlpatterns = [
    path('', ProductListView.as_view(), name = 'list'),
    path('group/<int:pk>', GroupListView.as_view(), name = 'group_list' ),
    path('<str:slug>', ProductDetailView.as_view(), name = 'details'),
]

search/urls.py
from django.urls import path, include

from .views import SearchView

app_name = 'search'
urlpatterns = [
    path('', SearchView.as_view(), name = 'search'),
]

search/views.py
from django.shortcuts import get_object_or_404, render
from django.views.generic import ListView, DetailView
# Create your views here.
from products.models import Product
from django.http import HttpResponse, HttpResponseRedirect
from django.urls import reverse
from django.http import JsonResponse
from django.core import serializers
from django.forms.models import model_to_dict


class SearchView(ListView):
    model = Product
    template_name = 'products/product_list.html'
    def get(self,*args, **kwargs):
        request = self.request
        search = request.GET.get('search')
        query = search
        if request.is_ajax():
            search = request.GET.get('search')
            query = search
        if query != "":
            print(query)
            products = Product.objects.filter(title__icontains = query)
            d = []
            for product in list(products)[:12]:
                pro = model_to_dict(product, fields=('title', 'price', 'active', 'slug'))
                if product.image:
                    pro['url'] =  product.image.url
                else:
                    pro['url'] = '/media/products/Profile-NotAvailable-300x300.png'
                d.append(pro)

            if len(d)==0:
                d = ['Sorry, not found']
            print(d)
            return JsonResponse({'products': d})
        else:
            return JsonResponse({'products': None})

        return super().get(request, *args, **kwargs)

templates/base.html
<!DOCTYPE html>
{% load static %}
<html>
  <head>
    <meta charset="utf-8">
    <title>BlueCube Shop</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'css/style.css'%}"/>
    <link href="https://cdn.jsdelivr.net/npm/select2@4.1.0-rc.0/dist/css/select2.min.css" rel="stylesheet" />
    <link rel="stylesheet" href="https://pro.fontawesome.com/releases/v5.10.0/css/all.css" integrity="sha384-AYmEC3Yw5cVb3ZcuHtOA93w35dYTsvhLPVnYs9eStHfGJvOvKxVfELGroGkvsg+p" crossorigin="anonymous"/>

  </head>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
  <script src="https://code.jquery.com/jquery-3.5.1.js"integrity="sha256-QWo7LDvxbWT2tbbQ97B53yJnYU3WhH/C8ycbRAkjPDc="crossorigin="anonymous"></script>
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
  <script src="https://ajax.googleapis.com/ajax/libs/jqueryui/1.11.4/jquery-ui.min.js" type="text/javascript"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/jqueryui-touch-punch/0.2.3/jquery.ui.touch-punch.min.js"></script>
  <script src="https://cdn.jsdelivr.net/npm/select2@4.1.0-rc.0/dist/js/select2.min.js"></script>
  <script src="https://js.stripe.com/v3/"></script>


  <body>
    <nav class="navbar navbar-expand navbar-light">
      <div class="container">
      <a class="navbar-brand" href="{% url 'index' %}">
        <img src="/media/products/icon.png" width="30" height="30"  class="d-inline-block align-top" alt="">
          BlueCube Shop
      </a>
      <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
        <ul class="navbar-nav mr-auto">
      <div class="navbar-nav">

        <li class = "nav-item {% if request.path == '/' %}active{% endif %}"><a class="nav-link " href="{% url 'index' %}">Home</span></a></li>
        <li><a href="{% url 'product:list' %}" class="nav-item nav-link  {% if request.path == '/products/' %}active{% endif %}"></a></li>
        <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="{% url 'index' %}" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
        Products
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
          <a class="dropdown-item" href="#">Women</a>
          <a class="dropdown-item" href="#">Men</a>
          <a class="dropdown-item" href="#">Kids</a>
          <a class="dropdown-item" href="#">Sports</a>
          <div class="dropdown-divider"></div>
          <a class="dropdown-item" href="{% url 'product:list' %}">All</a>
        </div>
      </li>
        {% if user.is_authenticated %}
              <li><a href="{% url 'accounts:logout' %}" class="nav-item nav-link mr">Log out</a></li>
        {% else %}
              <li><a href="{% url 'accounts:login' %}" class="nav-item nav-link ">Log in</a></li>
              <li><a href="{% url 'accounts:register' %}" class="nav-item nav-link ">Sign up</a></li>

        {% endif %}
            <li><a href="{% url 'carts:home' %}" class="nav-item nav-link ml-auto"><i class="fas fa-shopping-cart">   {{request.session.cart_item}}</i></a></li>
            </ul>
            {% include 'search.html' %}
      </div>
      </div>
        </div>
    </nav>
    <div class="container">
    <div class="search-output"> </div>
    </div>

    <div class="container mycontent">
          {% block content %}

          {% endblock %}

        </div>


  </body>

  <script src="{% static "js/master.js"%}" type="text/javascript" ></script>


</html>

templates/index.html
{% extends "base.html" %}
{% block content %}
{% load static %}
<link rel="stylesheet" href="{% static 'css/index_style.css'%}"/>

    <h1>BlueCube Shop</h1>
    <h2>Treat yourself with something nice</h2>
    <div class="products-list"></div>

<script src="{% static "js/index.js"%}" type="text/javascript" ></script>

{% endblock %}

templates/login.html
{% extends "base.html" %}
{% block content %}
{% load bootstrap4 %}

<div class="container">
  <form method="post">
    {% csrf_token %}
    {% bootstrap_form form  %}
    <input type="submit" class = 'btn btn-default' value="Sign up">
  </form>
</div>



{% endblock %}

templates/register.html
{% extends "base.html" %}
{% block content %}
{% load bootstrap4 %}

<div class="container">
  <form method="post">
    {% csrf_token %}
    {% bootstrap_form form  %}
    <input type="submit" class = 'btn btn-default' value="Sign up">
  </form>
</div>



{% endblock %}

templates/search.html
<form class="search-form form-inline my-2 my-lg-0" method="GET" action ='{% url "search:search" %}' class="search-form">
      <input class="form-control mr-sm-2" name = 'q' type="search" placeholder="Search" aria-label="Search">
    </select>
</form