billing/urls.py
from django.urls import path, include

from .views import payment_method_view, payment_method_createview
app_name = 'billing'
urlpatterns = [
    path('', payment_method_view, name='payment-method'),
    path('create/', payment_method_createview, name='payment-method-endpoint'),
]

carts/urls.py
from django.urls import path, include

from .views import cart_home, cart_update, checkout_home, CartSuccess, AddressUpdate
app_name = 'carts'
urlpatterns = [
    path('', cart_home, name='home'),
    path('update/', cart_update, name='update'),
    path('checkout/', checkout_home, name='checkout'),
    path('success/', CartSuccess.as_view(), name = 'success'),
    path('address-update/<int:pk>/',  AddressUpdate.as_view(), name = 'address_update')
]

ecommerce/urls.py
from django.conf.urls.static import static
from django.conf import settings
from django.contrib import admin
from django.urls import path, include
from .views import HomePage

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', HomePage.as_view(), name = 'index'),
    path('accounts/', include('accounts.urls')),
    path('products/', include('products.urls')),
    path('search/', include('search.urls')),
    path('carts/', include('carts.urls')),
    path('billing/', include('billing.urls')),
    path('analytics', include('analytics.urls'))
]


if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

billing/models.py
from django.db import models
from django.conf import settings
from django.db.models.signals import post_save, pre_save
from phone_field import PhoneField
User = settings.AUTH_USER_MODEL
# Create your models here.
import stripe
stripe.api_key = 'sk_test_51IXW3aCkhkhAd2s3znmhkXSYIzCuKI4eB46wGwcfFO5yjkx7eXCmfgfXq8sUiAltXuyZJti88K59JHvC2r9HavWG00dgpPm050'


class Address(models.Model):
    user        = models.OneToOneField(User, null=True, blank=True, on_delete=models.CASCADE, related_name='address')
    city        = models.CharField(max_length=50)
    street      = models.CharField(max_length=50)
    phone       = PhoneField(help_text='Contact phone')


class BillingProfile(models.Model):
    user        = models.OneToOneField(User, null=True, blank=True, on_delete=models.CASCADE, related_name='billing_profile')
    email       = models.EmailField()
    address     = models.ForeignKey(Address, null=True, blank=True, on_delete = models.CASCADE)
    active      = models.BooleanField(default=True)
    update      = models.DateTimeField(auto_now=True)
    timestamp   = models.DateTimeField(auto_now_add=True)
    customer_id = models.CharField(max_length=120, null=True, blank = True)


    def __str__(self):
        return self.email

def billing_profile_created_receiver(sender,instance,*args,**kwargs):
    if not instance.customer_id:
        customer = stripe.Customer.create(
            email = instance.email
        )
        instance.customer_id = customer.id

pre_save.connect(billing_profile_created_receiver, sender = BillingProfile)

def user_created_receiver(sender, instance, created, *args, **kwargs):
    if created and instance.email:
        BillingProfile.objects.get_or_create(user=instance, email=instance.email)

post_save.connect(user_created_receiver, sender=User)

billing/forms.py
from django import forms
from .models import Address

class AddressForm(forms.ModelForm):
    class Meta:
        model = Address
        exclude=['user']

billing/views.py
from django.shortcuts import render
from django.http import JsonResponse, HttpResponse
# Create your views here.


import stripe
stripe.api_key = 'sk_test_51IXW3aCkhkhAd2s3znmhkXSYIzCuKI4eB46wGwcfFO5yjkx7eXCmfgfXq8sUiAltXuyZJti88K59JHvC2r9HavWG00dgpPm050'
STRIPE_PUB_KEY = 'pk_test_51IXW3aCkhkhAd2s3FSB27u0ycISe07B0tQEGMhcKmqfZDDv2rMxIRAebwsd0EYrtCFPCurNhewcrrBqop69axiFv00vLk5rsta'

def payment_method_view(request):
    return render(request,'billing/payment-method.html', {'publish_key': STRIPE_PUB_KEY})

def payment_method_createview(request):
    if request.method == 'POST':
        return JsonResponse({'message': 'Done'})
    return HttpResponse('error', status_code=402)

billing/templates/billing/payment-method.html
{% extends "base.html" %}
{% block content %}
<div class = 'col-10 col-md-6 mx-auto'>
<h1>Add Payment Method</h1>
<form action="{% url 'billing:payment-method-endpoint' %}" method="post" id="payment-form" data-token='{{publish_key}}' data-next-url='/billing'>
  {% csrf_token %}
  <div class="form-row">
    <label for="card-element">
      Credit or debit card
    </label>
    <div id="card-element" class='form-control'>
      <!-- A Stripe Element will be inserted here. -->
    </div>

    <!-- Used to display Element errors. -->
    <div id="card-errors" role="alert"></div>
  </div>

  <button class='btn btn-primary mr-3'>Submit Payment</button>
</form>
</div>

<script>
const stripe = Stripe('pk_test_51IXW3aCkhkhAd2s3FSB27u0ycISe07B0tQEGMhcKmqfZDDv2rMxIRAebwsd0EYrtCFPCurNhewcrrBqop69axiFv00vLk5rsta');
const elements = stripe.elements();




const style = {
  base: {
    // Add your base input styles here. For example:
    fontSize: '16px',
    color: '#32325d',
  },
};

// Create an instance of the card Element.
const card = elements.create('card', {style});

// Add an instance of the card Element into the `card-element` <div>.
card.mount('#card-element');



const stripeTokenHandler = (token) => {
  // Insert the token ID into the form so it gets submitted to the server
  const form = document.getElementById('payment-form');
  const hiddenInput = document.createElement('input');
  hiddenInput.setAttribute('type', 'hidden');
  hiddenInput.setAttribute('name', 'stripeToken');
  hiddenInput.setAttribute('value', token.id);
  form.appendChild(hiddenInput);

  // Submit the form
  form.submit();
}





</script>
{% endblock %}